BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'legaltech_loader') THEN
        CREATE ROLE legaltech_loader NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'legaltech_app') THEN
        CREATE ROLE legaltech_app NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'legaltech_analyst') THEN
        CREATE ROLE legaltech_analyst NOLOGIN;
    END IF;
END;
$$;

REVOKE ALL ON SCHEMA staging, core, analytics FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA staging, core, analytics FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA staging, core, analytics FROM PUBLIC;

GRANT USAGE ON SCHEMA staging TO legaltech_loader;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA staging TO legaltech_loader;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA staging TO legaltech_loader;
GRANT EXECUTE ON PROCEDURE staging.promote_batch(bigint) TO legaltech_loader;

GRANT USAGE ON SCHEMA core TO legaltech_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA core TO legaltech_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core TO legaltech_app;

GRANT USAGE ON SCHEMA analytics TO legaltech_analyst;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO legaltech_analyst;

ALTER DEFAULT PRIVILEGES IN SCHEMA staging REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO legaltech_loader;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT USAGE, SELECT ON SEQUENCES TO legaltech_loader;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE ON TABLES TO legaltech_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO legaltech_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO legaltech_analyst;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics REVOKE ALL ON FUNCTIONS FROM PUBLIC;

COMMIT;
